### ISSUE TITLE
Passing max-warning flag?

### ISSUE THREAD

**Issue by roderickhsiao** [lesshint/gulp-lesshint#17]
Thanks for building the library! 

We are facing one issue that there are too many warnings, the all results are gone silently. 
https://github.com/lesshint/lesshint provides a flag `max-warning` on cli, set to `-1` could print out all the log.

Is that possible to add support on the gulp plugin?

Thanks

**Comment by jwilsson** [comment]
I've been thinking about this myself and have some plans on exposing the `max-warning` logic in `lesshint` for use by other tools/libraries. Once that's done I'll include it here too. Hang tight!

**Comment by slamflipstrom** [comment]
Our team would love to utilize that `max-warning` flag in our build as well. Any word on progress here?

**Comment by jwilsson** [comment]
@slamflipstrom Nothing yet, I'm afraid. 

But I think we could go for a solution in `gulp-lesshint` instead of exposing something in the main `lesshint` library. Would anyone of you, @roderickhsiao or @slamflipstrom be interested in submitting a PR for it? 

I'm thinking something like a `maxWarnings` option passed the same way as `configPath` and then throwing an error if above that threshold.

**Comment by dman777** [comment]
I am for this as well, just hit this issue today and happy to find this issue created.
